-- =============================================================
-- Pattern A: Month-partitioned tables + UNION ALL view
-- =============================================================
-- Each calendar month of snapshot_date is a physically separate
-- table. A view stitches them together for consumers.
--
-- Data profile:
--   prop_cd       — 8,000 distinct values (sort key, leading column)
--   snapshot_date — partition key driving the UNION ALL split
--   extract_date  — ETL load timestamp, sort key trailing column
--   ~1,000 rows per prop_cd per snapshot day → ~8M rows/day
-- =============================================================

-- ── Column encoding rationale ──────────────────────────────────
-- prop_cd       ZSTD     — 8,000 levels exceeds BYTEDICT limit (256);
--                          ZSTD gives best compression on high-cardinality
--                          short strings and is CPU-efficient on modern HW.
-- snapshot_date RUNLENGTH — within a monthly partition all dates cluster
--                           tightly; run-length is near-ideal here.
-- extract_date  RUNLENGTH — same rationale; lags snapshot_date by 0-3 days
--                           so runs are very long within a partition.
-- ──────────────────────────────────────────────────────────────

-- Base table DDL (stamped once per YYYYMM partition by schema_manager.py)
-- {period} is substituted with e.g. 202401, 202402, …

CREATE TABLE IF NOT EXISTS benchmark.prop_snapshot_{period} (
    prop_cd         VARCHAR(20)   NOT NULL ENCODE ZSTD,
    snapshot_date   DATE          NOT NULL ENCODE RUNLENGTH,
    extract_date    DATE          NOT NULL ENCODE RUNLENGTH
)
DISTSTYLE KEY
DISTKEY  (prop_cd)
-- Compound sort key: prop_cd first because the dominant access pattern is
-- "all snapshots for a given property over a date range". Having prop_cd
-- as the leading key means Redshift can skip most blocks on a per-property
-- filter, then snapshot_date and extract_date provide further ordering
-- for range scans within a property's rows.
COMPOUND SORTKEY (prop_cd, snapshot_date, extract_date);


-- ── Union view ─────────────────────────────────────────────────
-- Regenerated by schema_manager.py whenever a new monthly partition
-- is added. The {union_selects} placeholder is replaced programmatically.
-- Agent note: do not edit this block manually — it is template-only.

-- CREATE OR REPLACE VIEW benchmark.prop_snapshot_v AS
--     SELECT * FROM benchmark.prop_snapshot_202401
--     UNION ALL
--     SELECT * FROM benchmark.prop_snapshot_202402
--     ...;

